/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Chip: typeof import('primevue/chip')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputColor: typeof import('primevue/inputcolor')['default']
    InputColorArea: typeof import('primevue/inputcolorarea')['default']
    InputColorAreaBackground: typeof import('primevue/inputcolorareabackground')['default']
    InputColorAreaHandle: typeof import('primevue/inputcolorareahandle')['default']
    InputColorEyeDropper: typeof import('primevue/inputcoloreyedropper')['default']
    InputColorInput: typeof import('primevue/inputcolorinput')['default']
    InputColorSlider: typeof import('primevue/inputcolorslider')['default']
    InputColorSliderHandle: typeof import('primevue/inputcolorsliderhandle')['default']
    InputColorSliderTrack: typeof import('primevue/inputcolorslidertrack')['default']
    InputColorSwatch: typeof import('primevue/inputcolorswatch')['default']
    InputColorSwatchBackground: typeof import('primevue/inputcolorswatchbackground')['default']
    InputColorTransparencyGrid: typeof import('primevue/inputcolortransparencygrid')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Popover: typeof import('primevue/popover')['default']
  }
}
